sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - '11'
branches:
  only:
  - travis-ci
before_script:
  - npm install
  - ./node_modules/.bin/chromedriver &
  - sleep 5
script:
  - node tests/test.js
