npm run test:api
npm run test:superagent
npm run test:mocha
npm run test:nightmare
npm run test:chai
npm run test:nightwatchapi
npm run test:nightwatch
npm run test:javascript
npm run test:webdriverio
npm run test:webdriver
npm run test:protractor
